import { StockQuote, NewsItem } from "./types";

export const MOCK_QUOTES: Record<string, StockQuote> = {
  AAPL: { ticker: "AAPL", price: 178.72, change: -2.15, changePercent: -1.19, previousClose: 180.87 },
  MSFT: { ticker: "MSFT", price: 428.50, change: 3.20, changePercent: 0.75, previousClose: 425.30 },
  NVDA: { ticker: "NVDA", price: 131.28, change: 5.47, changePercent: 4.35, previousClose: 125.81 },
  GOOGL: { ticker: "GOOGL", price: 175.98, change: -0.82, changePercent: -0.46, previousClose: 176.80 },
  AMZN: { ticker: "AMZN", price: 198.42, change: 1.56, changePercent: 0.79, previousClose: 196.86 },
  TSLA: { ticker: "TSLA", price: 248.50, change: -8.30, changePercent: -3.23, previousClose: 256.80 },
  META: { ticker: "META", price: 582.10, change: 7.90, changePercent: 1.38, previousClose: 574.20 },
  AMD: { ticker: "AMD", price: 162.35, change: 4.12, changePercent: 2.60, previousClose: 158.23 },
  NFLX: { ticker: "NFLX", price: 912.50, change: 12.30, changePercent: 1.37, previousClose: 900.20 },
  COIN: { ticker: "COIN", price: 265.80, change: -5.40, changePercent: -1.99, previousClose: 271.20 },
};

export const MOCK_NEWS: NewsItem[] = [
  {
    title: "NVIDIA, 차세대 AI 칩 'Blackwell Ultra' 양산 가속화",
    summary: "NVIDIA가 차세대 AI 가속기 Blackwell Ultra의 양산 일정을 앞당겼다. 데이터센터 수요 급증에 대응하기 위한 조치로, AMD와의 경쟁에서도 유리한 고지를 점할 전망이다.",
    source: "Reuters",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: ["NVDA", "AMD"],
    sentiment: "positive",
  },
  {
    title: "Apple, EU 디지털 시장법 벌금 가능성 제기",
    summary: "유럽연합 규제 당국이 Apple의 App Store 정책이 디지털 시장법을 위반했다고 판단, 최대 매출의 10%에 해당하는 벌금이 부과될 수 있다.",
    source: "Bloomberg",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: ["AAPL"],
    sentiment: "negative",
  },
  {
    title: "Tesla, 중국 판매량 전월 대비 15% 감소",
    summary: "Tesla의 3월 중국 내 신규 등록 대수가 전월 대비 15% 감소했다. BYD 등 현지 경쟁사의 공격적 가격 전략이 주요 원인으로 분석된다.",
    source: "CNBC",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: ["TSLA"],
    sentiment: "negative",
  },
  {
    title: "Meta, Threads 월간 활성 이용자 3억 명 돌파",
    summary: "Meta의 텍스트 기반 SNS Threads가 월간 활성 이용자 3억 명을 돌파했다. 광고 수익화가 본격화되면서 수익 기여가 기대된다.",
    source: "TechCrunch",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: ["META"],
    sentiment: "positive",
  },
  {
    title: "FOMC 의사록 공개 — 금리 인하 시점 불확실성 지속",
    summary: "연준 FOMC 의사록에 따르면 위원들 사이에서 금리 인하 시점에 대한 의견이 엇갈린 것으로 나타났다. 시장 변동성 확대 가능성에 유의해야 한다.",
    source: "Fed Reserve",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: [],
    sentiment: "neutral",
  },
  {
    title: "Microsoft, OpenAI와 데이터센터 100억 달러 투자 계획",
    summary: "Microsoft가 OpenAI와 공동으로 미국 내 AI 데이터센터에 100억 달러 규모의 투자를 계획 중이다. Azure AI 서비스 확대의 핵심 인프라가 될 전망이다.",
    source: "WSJ",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: ["MSFT"],
    sentiment: "positive",
  },
  {
    title: "Amazon, AWS 신규 AI 서비스 출시로 클라우드 경쟁 강화",
    summary: "Amazon Web Services가 기업용 생성형 AI 서비스를 대폭 확대했다. Bedrock 플랫폼의 신규 모델 추가로 Microsoft Azure, Google Cloud와의 경쟁이 더욱 치열해질 전망이다.",
    source: "The Verge",
    url: "#",
    publishedAt: new Date().toISOString(),
    relatedTickers: ["AMZN", "MSFT", "GOOGL"],
    sentiment: "positive",
  },
];
